title: Arie-1
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://github.com/Arie-1/Arie-1.github.io.git" # the base hostname & protocol for your site, e.g. http://example.com
permalink: ':title/'
blog_theme: dark # Or use dark

# Profile information
name: Arie-1
tagline: yongmoon high school student  
about-description: somniant papilionem (꿈꾸는 나비) # Add Discription
pic: asdd.png  # Place a 200x200 picture inside /assets/img/ folder and provide the name of the file below

# Contact links
email: yofireboy@gmial.com # Add your Email address
phone: 010-9536-6685 # Add your Phone number
website:  https://arie-1.github.io/ # Add your website, do not add http://
linkedin: # Add your Linkedin handle
github: https://github.com/Arie-1 # Add your Github handle
instagram: '@derehan0506' # Add your Twitter handle

# Tracker
analytics:

# Comments
discus-identifier: # Add your Disqus identifier

# Important settings
assets:
  sources:
    - assets/fonts
    - assets/img
    - assets/js
    - assets/stylesheets

# Build settings
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md

gems:
  - jekyll-feed
  - jekyll-assets
exclude:
  - Gemfile
  - Gemfile.lock

include: [_pages]
